### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by RobertLbebber** [RobertLbebber/NukeReactor#11]
- [ ] Ensure working components are subjected to the legal scrutiny:

1. Payment and Limits on transactions.
2. Communication and Associations are recorded and providable on request.
3. Account Accountability
4. EULA
5. Privacy and Transprency
6. User Data and Maintence
7. Security and Breaches

- [ ] Handle Software and Physical ownership

- [ ] Patents, Trademarks and Branding

- [ ] Employee Contract

- [ ] Ownership and Shares
