### ISSUE TITLE
Fund Raises in Time 

### ISSUE THREAD

**Issue by RobertLbebber** [RobertLbebber/NukeReactor#35]
- [ ] Develop Money UI
NukeReactor #53
- [ ] Charts Metrics and Interactive Filters
NukeReactor #54
- [ ] Money Flow Patterns
NukeReactor #55
