### ISSUE TITLE
Locational Map with Metric Filters

### ISSUE THREAD

**Issue by RobertLbebber** [RobertLbebber/NukeReactor#37]
- [ ] Create an Interactive Map
NukeReactor #43
- [ ] Provide Map with Metric Filters
NukeReactor #44
- [ ] Identify Key Areas and Regions
NukeReactor #45
- [ ] Postable Notes to Locations
NukeReactor #46
- [ ] Trackable Trends and Activities
NukeReactor #47
